version: '3.8'

services:
  web:
    build: ./
    restart: always
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - staticfiles:/app/staticfiles/
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env

volumes:
  staticfiles: