# Generated by Django 4.2 on 2025-02-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlucoseLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=256)),
                ('device', models.CharField(max_length=256)),
                ('serial_number', models.CharField(max_length=256)),
                ('recording_type', models.SmallIntegerField()),
                ('value', models.IntegerField()),
            ],
        ),
    ]
